version: '3.9'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: "finance_frontend"
    environment:
      - NODE_ENV:local
    env_file:
      - .env.production
    ports:
      - 3000:3000
