name: Docker Image CI #Pipeline's name

on:
  push:
    branches: [ "main" ]

jobs:

  build: #stage's name

    runs-on: self-hosted #os base

    steps:
    - uses: actions/checkout@v4
    - name: Build Backend... #step's name
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        APP_KEYS: ${{ secrets.APP_KEYS }}
        API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
        ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
        DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
        DATABASE_FILENAME: ${{ secrets.DATABASE_FILENAME }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

      run: | #script
        cd prod 
        docker compose up -d 
