name: Docker Image CI #Pipeline's name

on:
  push:
    branches: [ "main" ]

jobs:

  build: #stage's name

    runs-on: self-hosted #os base

    steps:
    - uses: actions/checkout@v4
    - name: Build Backend... #step's name
      run: | #script
        cd prod 
        chmod +x ./setup_env.sh
        touch .env
        ./setup_env.sh
        docker compose up -d 
